### ISSUE TITLE
Incorrect app name in Camera & Microphone history.

### ISSUE THREAD

**Issue by AaronFeng753** [CraZyLegenD/Vigilante#28]
All the camera and microphone usage is immediately detected, but some app's name is not recorded correctly, for example wechat is recorded as Vigilante for some reason.

Device : Xiaomi mi 9, Android 10 (Derpfest, not MIUI)

App version: 1.0.2

![photo_2020-11-17_18-17-58](https://user-images.githubusercontent.com/52553688/99377669-720b9580-2901-11eb-997c-253c3bfbbdf9.jpg)

**Comment by CraZyLegenD** [comment]
Camera & microphone history would be removed in the future releases due to the fact that Android hasn't provided us developers with a way to get the package using the camera at the moment, so what does the app do? It tries to see which is the current package that you've opened and that is inconsistent, since the mic can be accessed in the background by totally different app and you've opened up for example Calculator and the app will catch that Calculator is using your microphone.

**Comment by AaronFeng753** [comment]
Thank you for your explanation
